version: 2.1

jobs:
  frontend_build:
    docker:
      - image: circleci/node:8.12.0
    working_directory: ~/project
    steps:  
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-deps-{{ .Branch }}
            - v1-deps
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run: npm eslint
      - run: npm test 
      - run: $(npm bin)/cypress run

workflows:
  version: 2

  my_workflow:
    jobs:
      - frontend_build:
          context: build
          filters:
            branches:
              only:
                - main
